export default defineAppConfig({
  pages: [
    'pages/role/index',
    'pages/login/index',
    'pages/family/dashboard/index',
    'pages/family/moods/index',
    'pages/family/interactions/index',
    'pages/family/messages/index',
    'pages/family/care/index',
    'pages/family/alerts/index',
    'pages/family/profile/index',
    'pages/family/reports/index',
    'pages/family/counseling/index',
    'pages/family/media/index',
    'pages/family/media-detail/index',
    'pages/elderly/home/index',
    'pages/elderly/companion/index',
    'pages/elderly/memories/index',
    'pages/elderly/record/index',
    'pages/elderly/reminders/index',
    'pages/elderly/help/index',
    'pages/elderly/counseling/index',
    'pages/elderly/profile/index',
    'pages/elderly/media/index',
    'pages/elderly/media-history/index',
    'pages/service/workspace/index',
    'pages/service/cases/index',
    'pages/service/case-detail/index',
    'pages/service/tasks/index',
    'pages/service/followup/index',
    'pages/service/profile/index',
  ],
  window: {
    navigationBarBackgroundColor: '#FAFAFF',
    navigationBarTextStyle: 'black',
    navigationBarTitleText: 'KinEcho',
    backgroundColor: '#FAFAFF',
    backgroundTextStyle: 'dark',
  },
  permission: {
    'scope.record': {
      desc: '用于AI陪伴语音输入，把您说的话转成文字后发送给小心回复',
    },
  },
});
