export default defineAppConfig({
  pages: [
    'pages/role/index',
    'pages/login/index',
    'pages/legal/user-agreement/index',
    'pages/legal/privacy-policy/index',
  ],
  subPackages: [
    {
      root: 'pages/family',
      pages: [
        'dashboard/index',
        'moods/index',
        'interactions/index',
        'messages/index',
        'care/index',
        'alerts/index',
        'profile/index',
        'reports/index',
        'counseling/index',
        'media/index',
        'media-detail/index',
        'bind-elderly/index',
      ],
    },
    {
      root: 'pages/elderly',
      pages: [
        'home/index',
        'companion/index',
        'memories/index',
        'record/index',
        'record-history/index',
        'reminders/index',
        'help/index',
        'counseling/index',
        'psychological-consulting/index',
        'psychology-question/index',
        'mental-screening/index',
        'psychology-video/index',
        'counselor-list/index',
        'counselor-detail/index',
        'counselor-article/index',
        'profile/index',
        'basic-info/index',
        'family-bindings/index',
        'media/index',
        'media-history/index',
      ],
    },
    {
      root: 'pages/service',
      pages: [
        'workspace/index',
        'consultations/index',
        'cases/index',
        'case-detail/index',
        'schedule/index',
        'tasks/index',
        'followup/index',
        'profile/index',
        'certification/index',
        'no-access/index',
        'review-pending/index',
      ],
    },
  ],
  window: {
    navigationBarBackgroundColor: '#FAFAFF',
    navigationBarTextStyle: 'black',
    navigationBarTitleText: 'KinEcho',
    backgroundColor: '#FAFAFF',
    backgroundTextStyle: 'dark',
  },
  permission: {
    'scope.record': {
      desc: '用于AI陪伴语音输入，把您说的话转成文字后发送给小心回复',
    },
  },
});
